server:
  port: 8091

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb?currentSchema=public
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  cloud:
    gateway:
      routes:
        - id: report-service
          uri: http://report:8081
          predicates:
            - Path=/report/api/readers/**
          filters:
            - JwtAuthentication
        - id: reader-service
          uri: http://app:8080
          predicates:
            - Path=/library/api/readers
            - Method=POST
        - id: reader-service
          uri: http://app:8080
          predicates:
            - Path=/library/api/readers/**
          filters:
            - JwtAuthentication

management:
  endpoints:
    web:
      exposure:
        include: "*"