server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: report-service
          uri: http://report:8081
          predicates:
            - Path=/report/api/readers/**
        - id: reader-service
          uri: http://app:8080
          predicates:
            - Path=/library/api/readers/**

management:
  endpoints:
    web:
      exposure:
        include: "*"