server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: reader-service
          uri: http://localhost:8081
          predicates:
            - Path=/report/api/readers/**

management:
  endpoints:
    web:
      exposure:
        include: "*"